# Generated by Django 4.1.7 on 2023-02-19 01:25

from django.db import migrations, models
import mailing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего действия')),
                ('name', models.CharField(max_length=255, verbose_name='Тема')),
                ('image', models.ImageField(blank=True, null=True, upload_to=mailing.models.path_new_image, verbose_name='Картинка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор')),
                ('count_success', models.BigIntegerField(verbose_name='Доставлено')),
                ('count_error', models.BigIntegerField(verbose_name='Не дошло')),
                ('count_to_mailing', models.BigIntegerField(verbose_name='Всего')),
            ],
            options={
                'verbose_name': 'Сообщение всем',
                'verbose_name_plural': 'Сообщение всем',
            },
        ),
    ]
