# Generated by Django 4.1.7 on 2023-02-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(choices=[('Не отправлено', '1'), ('В процессе', '2'), ('Завершено', '3')], default='Не отправлено', max_length=30, verbose_name='Статус'),
        ),
    ]
