# Generated by Django 4.1.7 on 2023-02-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_mailing_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(choices=[('Не отправлено', '1'), ('В процессе', '2'), ('Завершено', '3')], default=('Не отправлено', '1'), max_length=30, verbose_name='Статус'),
        ),
    ]
