# Generated by Django 4.1.7 on 2023-02-19 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(choices=[(1, 'Не отправлено'), ('В процессе', 2), ('Завершено', 3)], default=1, max_length=30, verbose_name='Статус'),
        ),
    ]
