# Generated by Django 4.1.7 on 2023-02-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='count_error',
            field=models.BigIntegerField(default=0, verbose_name='Не дошло'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='count_success',
            field=models.BigIntegerField(default=0, verbose_name='Доставлено'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='count_to_mailing',
            field=models.BigIntegerField(default=0, verbose_name='Всего'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(choices=[('Не отправлено', 1), ('В процессе', 2), ('Завершено', 3)], default=1, max_length=30, verbose_name='Статус'),
        ),
    ]
