# Generated by Django 4.1.7 on 2023-02-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_alter_mailing_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(blank=True, choices=[(1, 'Не отправлено'), (2, 'В процессе'), (3, 'Завершено')], default=1, max_length=255, null=True, verbose_name='Статус'),
        ),
    ]
