# Generated by Django 4.1.7 on 2023-02-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_alter_mailing_status_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status_send',
            field=models.CharField(choices=[('Не отправлено', 'Не отправлено'), ('В процессе', 'В процессе'), ('Завершено', 'Завершено')], default='Не отправлено', max_length=255, verbose_name='Статус'),
        ),
    ]
