# Generated by Django 4.1.7 on 2023-02-19 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0015_alter_mailing_status_send'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mailing',
            new_name='MailingModel',
        ),
    ]
