# Generated by Django 4.1.7 on 2023-02-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0016_rename_mailing_mailingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmodel',
            name='date_last_modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Данные актуальны на'),
        ),
    ]
