# Generated by Django 4.1.7 on 2023-02-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_botmodel_date_last_modified_and_more'),
        ('mailing', '0019_alter_mailingmodel_channel_alter_mailingmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmodel',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.botmodel', verbose_name='Бот для рассылки'),
        ),
    ]
