# Generated by Django 4.1.7 on 2023-02-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0020_alter_mailingmodel_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingmodel',
            old_name='channel',
            new_name='bot',
        ),
    ]
