# Generated by Django 4.1.7 on 2023-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0021_rename_channel_mailingmodel_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingmodel',
            name='time_finish_sleep',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало сна'),
        ),
        migrations.AddField(
            model_name='mailingmodel',
            name='time_start_sleep',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало сна'),
        ),
    ]
