# Generated by Django 4.1.5 on 2023-01-27 16:51

from django.db import migrations, models
import django.db.models.deletion
import src.product.product_new.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_base', '0001_initial'),
        ('params', '0001_initial'),
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductParametersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего действия')),
                ('parameter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.wordsmodel', verbose_name='Параметр')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_base.baseproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Параметры названия',
                'verbose_name_plural': 'Параметры названия',
            },
        ),
        migrations.CreateModel(
            name='NewProductModel',
            fields=[
                ('baseproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_base.baseproduct')),
                ('text_post', models.TextField(verbose_name='Описание')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='params.seriesmodel', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Новый товар',
                'verbose_name_plural': 'Новые товары',
                'ordering': ('id',),
            },
            bases=('product_base.baseproduct',),
        ),
        migrations.CreateModel(
            name='ImageNewProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего действия')),
                ('image', models.ImageField(upload_to=src.product.product_new.models.path_new_image, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_new.newproductmodel', verbose_name='Новый товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
