# Generated by Django 4.1.7 on 2023-02-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_last_modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего действия')),
                ('name_channel', models.CharField(max_length=255, verbose_name='Название канала')),
                ('id_bot', models.CharField(max_length=255, verbose_name='Токен бота')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='id_channel',
            field=models.CharField(default=1, max_length=255, verbose_name='Название канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='name_channel',
            field=models.CharField(default=1, max_length=255, verbose_name='Название канала'),
            preserve_default=False,
        ),
    ]
