# Generated by Django 4.1.7 on 2023-02-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_botmodel_channelmodel_id_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='count_members',
            field=models.BigIntegerField(default=0, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='channelmodel',
            name='id_channel',
            field=models.CharField(max_length=255, verbose_name='ID канала'),
        ),
    ]
