# Generated by Django 4.1.7 on 2023-02-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channelmodel_count_members_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelmodel',
            old_name='name_channel',
            new_name='name',
        ),
    ]
