# Generated by Django 4.1.7 on 2023-02-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_rename_name_channel_channelmodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmodel',
            old_name='name_channel',
            new_name='name',
        ),
        migrations.AddField(
            model_name='botmodel',
            name='count_members',
            field=models.BigIntegerField(default=0, verbose_name='Участники'),
        ),
    ]
