# Generated by Django 4.1.7 on 2023-02-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_rename_name_channel_botmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='count_all_time',
            field=models.BigIntegerField(default=0, verbose_name='За все время'),
        ),
        migrations.AlterField(
            model_name='botmodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название бота'),
        ),
    ]
