# Generated by Django 4.1.7 on 2023-02-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_channelmodel_count_all_time_alter_botmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='count_all_time',
            field=models.BigIntegerField(default=0, verbose_name='За все время'),
        ),
    ]
