# Generated by Django 4.1.7 on 2023-02-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_botmodel_date_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel.channelmodel', verbose_name='Канал'),
            preserve_default=False,
        ),
    ]
