# Generated by Django 4.1.7 on 2023-02-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_botmodel_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='text',
            field=models.TextField(default=1, help_text='Макс. 1024 символа', max_length=1024, verbose_name='Текст приветствия'),
            preserve_default=False,
        ),
    ]
