# Generated by Django 4.1.7 on 2023-02-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='tg_id',
            new_name='telegram_id',
        ),
    ]
