# Generated by Django 4.1.7 on 2023-02-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usermodel_bot_usermodel_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='bot',
        ),
    ]
