# Generated by Django 4.1.7 on 2023-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_usermodel_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='telegram_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID телеграм'),
        ),
    ]
