# Generated by Django 4.1.7 on 2023-02-20 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_botmodel_date_last_modified_and_more'),
        ('user', '0005_alter_usermodel_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='channel',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channel.botmodel', verbose_name='Канал'),
            preserve_default=False,
        ),
    ]
