# Generated by Django 4.1.7 on 2023-02-20 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_botmodel_channel'),
        ('user', '0006_remove_usermodel_channel_usermodel_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.botmodel', verbose_name='Бот'),
        ),
    ]
